version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: mylemp.nginx
        ports:
            - ${NGINX_HTTP_PORT}:80
            - ${NGINX_HTTPS_PORT}:443
        restart: always
        volumes:
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
            - ./etc/ssl:/etc/ssl
            - ${VOLUME_WORKDIR}:/var/www/html
        depends_on:
            - php
            - mysql
    php:
        build: ./etc/php
        container_name: mylemp.php
        restart: always
        volumes:
            - ./etc/php/conf.d:/usr/local/etc/php/conf.d
            - ./logs/php:/var/log/php
            - ${VOLUME_WORKDIR}:/var/www/html
    composer:
        image: composer
        container_name: mylemp.composer
        command: install
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: mylemp.phpmyadmin
        ports:
            - ${PMA_LISTEN_PORT}:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mylemp.mysql
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql
        container_name: mylemp.mysql
        restart: always
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_LISTEN_PORT}:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
